<a href="https://colab.research.google.com/github/Sunber2111/FDR/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout
from tensorflow.keras.models import Model,Sequential

In [2]:
data = np.load('./data_pca_35_y_mean.pickle.npz')

In [3]:
X = data['arr_0']
y = data['arr_1']
mean = data['arr_2']

In [4]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y)
x_train[0]

array([ 0.08629481,  0.97915448, -2.13224271,  1.21033235,  0.10394724,
       -0.3710297 ,  1.13757957, -0.33360254,  0.68722758, -0.25685242,
        1.00854197, -0.3142619 , -1.35378344,  0.91639695,  1.56092186,
        0.78641104, -0.71761867, -0.70041253,  0.58786935,  1.66709878,
       -0.43706365,  0.78056094,  0.57171764, -2.18992827,  0.41630705,
        0.8404765 , -0.12552434,  0.8439947 , -0.7936337 ,  1.04868232,
        1.48417482, -1.02767032, -0.46515526,  0.49962169,  0.98561076])

In [10]:
x_train[0].shape

(35,)

## Model


In [6]:
# Build Model using function API

K = len(set(y_train))

i = Input(shape=x_train[0].shape)
x = Flatten()(i)
x = Dropout(0.5)(x)
x = Dense(1024,activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(K,activation='softmax')(x)

model = Model(i,x)

In [7]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
r = model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 51ms/step - loss: 0.0184 - accuracy: 1.0000 - val_loss: 0.4049 - val_accuracy: 0.8571
Epoch 2/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0102 - accuracy: 1.0000 - val_loss: 0.4032 - val_accuracy: 0.8571
Epoch 3/100
1/1 [==============================] - 0s 17ms/step - loss: 0.0151 - accuracy: 1.0000 - val_loss: 0.4017 - val_accuracy: 0.8571
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0229 - accuracy: 1.0000 - val_loss: 0.4010 - val_accuracy: 0.8571
Epoch 5/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0098 - accuracy: 1.0000 - val_loss: 0.4006 - val_accuracy: 0.8571
Epoch 6/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0676 - accuracy: 0.9643 - val_loss: 0.4018 - val_accuracy: 0.8571
Epoch 7/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0550 - accuracy: 1.0000 - val_loss: 0.4036 - val_accuracy: 0.8571
Epoch 8/100
1/1 [===

In [38]:
p_test = model.predict(x_test).argmax(axis=1)

In [39]:
p_test

array([1, 0, 0, 0, 0, 0, 0])

In [40]:
y_test

array([1, 1, 1, 0, 0, 0, 0], dtype=int32)

In [36]:
rs = np.where(y_train != p_test)
len(rs)

1